In [59]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import cv2  # redd and show the image 
import random as r


In [60]:
# to use for image read/write/show processing
#!pip install opencv-python

In [61]:
arr = cv2.imread("baby1_image.jpeg")

In [62]:
arr2D = arr.reshape((arr.shape[0]*arr.shape[1],3)) # 
print(arr2D.shape)

(72600, 3)


### Initialization of k Centroids

In [63]:
k = 3   # Select centroids from the give image pixels
centroids = np.zeros((k,3))
for i in range(k):
    
    row_idx = r.randint(0,arr.shape[0])
    
    centroids[i,:] = arr2D[row_idx,:]
    
print(centroids)

[[ 89. 141. 154.]
 [115. 134. 107.]
 [ 77. 137. 106.]]


In [64]:
import heapq  # to store the min distance centroid efficiently 


In [65]:
clusters_arr = np.zeros((arr2D.shape[0],3))

for i in range(100):
    selected_centroid_row = np.zeros(arr2D.shape[0])
    
    for row in range(arr2D.shape[0]):  # CALCULATE THE DISTANCE FOR EACH PIXEL,FROM EACH DISTANCE 
        min_dis_centroids = [] 
        for clus in range(k):
            #print(clus)
            #print(np.sum(np.abs(row - centroids[clus,:])))
            dist = np.sum(np.abs(arr2D[row] - centroids[clus,:])) # CALCULATE THE DISTANCE
            # 
            heapq.heappush(min_dis_centroids, (dist, clus) )  #make min heap on
                                                     # basis tuple[0]("Cluster distance") index, also store the cluster name
                                                     # to get min cluster and its name easily


        #heapq.heapify(min_dis_centroids)
        #print(min_dis_centroids)
        #print(min_dis_centroids[0][1])
       
        selected_centroid_row[row] = min_dis_centroids[0][1] # min distance value on the zero index,(tuple)[1] for "cluster NO"
    print('iteration',i)
  
    print(centroids)
    print()
    for c in range(k): # 
        
        group_rows = arr2D[selected_centroid_row == c]
        
        centroids[c,:] = np.mean(group_rows,axis=0) # Update the centroids WITH MEAN OF SAME CLUSTER (i.e c1, c2)
print('Finished: ') 
print('final centroids ',centroids)

iteration 0
[[ 89. 141. 154.]
 [115. 134. 107.]
 [ 77. 137. 106.]]

iteration 1
[[175.70893538 202.27176226 193.68500133]
 [114.9727321  152.21846154 121.32636605]
 [ 68.80527395 110.25006925  90.58168523]]

iteration 2
[[210.06514354 215.27226404 216.91570639]
 [106.29174853 171.87062505 135.15116787]
 [ 67.95870891  90.42238865  85.53532609]]

iteration 3
[[219.02177941 218.67440541 223.64249253]
 [109.51856994 173.79022435 138.41847843]
 [ 68.530632    87.20965288  84.16125017]]

iteration 4
[[220.70767433 219.74479938 224.80338917]
 [110.99027171 174.20816681 139.74895436]
 [ 68.67624377  87.92247321  84.42318979]]

iteration 5
[[221.12518652 220.00887458 225.10531689]
 [111.53765042 174.59170698 140.25347351]
 [ 68.95352586  88.63754197  84.86017461]]

iteration 6
[[221.2208671  220.08084822 225.16917145]
 [111.79376521 174.93347064 140.53610435]
 [ 69.2902352   89.33410412  85.3239297 ]]

iteration 7
[[221.2208671  220.08084822 225.16917145]
 [111.89786834 175.12680251 140.657962

iteration 59
[[221.35231485 220.16038331 225.24347346]
 [112.17143849 175.51589381 141.0107958 ]
 [ 69.89532866  90.54160509  86.07774851]]

iteration 60
[[221.35231485 220.16038331 225.24347346]
 [112.17143849 175.51589381 141.0107958 ]
 [ 69.89532866  90.54160509  86.07774851]]

iteration 61
[[221.35231485 220.16038331 225.24347346]
 [112.17143849 175.51589381 141.0107958 ]
 [ 69.89532866  90.54160509  86.07774851]]

iteration 62
[[221.35231485 220.16038331 225.24347346]
 [112.17143849 175.51589381 141.0107958 ]
 [ 69.89532866  90.54160509  86.07774851]]

iteration 63
[[221.35231485 220.16038331 225.24347346]
 [112.17143849 175.51589381 141.0107958 ]
 [ 69.89532866  90.54160509  86.07774851]]

iteration 64
[[221.35231485 220.16038331 225.24347346]
 [112.17143849 175.51589381 141.0107958 ]
 [ 69.89532866  90.54160509  86.07774851]]

iteration 65
[[221.35231485 220.16038331 225.24347346]
 [112.17143849 175.51589381 141.0107958 ]
 [ 69.89532866  90.54160509  86.07774851]]

iteration 66


In [66]:
centroids # Centroids 

array([[221.35231485, 220.16038331, 225.24347346],
       [112.17143849, 175.51589381, 141.0107958 ],
       [ 69.89532866,  90.54160509,  86.07774851]])

# UPDATE The Pixels color finally according to clusteres


In [67]:
for c in range(k):
    arr2D[selected_centroid_row == c] = centroids[c]

In [68]:
arr2D.shape = (arr.shape[0],arr.shape[1],arr.shape[2])


# Arange Shape of Array for image 

In [69]:
arr2D = arr2D.reshape(arr.shape)

In [70]:
cv2.imshow('image',arr2D) # not showing array

# DOWNLOAD THE IMAGE 

In [71]:
cv2.imwrite('image1_k3.jpg', arr2D)



True

### image_1 for 10 k

In [72]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import cv2  # redd and show the image 
import random as r


# to use for image read/write/show processing
#!pip install opencv-python

arr = cv2.imread("baby1_image.jpeg")




arr2D = arr.reshape((arr.shape[0]*arr.shape[1],3)) # 
print(arr2D.shape)



### Initialization of k Centroids

k = 10   # Select centroids from the give image pixels
centroids = np.zeros((k,3))
for i in range(k):
    
    row_idx = r.randint(0,arr.shape[0])
    
    centroids[i,:] = arr2D[row_idx,:]
    
print(centroids)

import heapq  # to store the min distance centroid efficiently 


# 

clusters_arr = np.zeros((arr2D.shape[0],3))

for i in range(50):
    selected_centroid_row = np.zeros(arr2D.shape[0])
    
    for row in range(arr2D.shape[0]):  # CALCULATE THE DISTANCE FOR EACH PIXEL,FROM EACH DISTANCE 
        min_dis_centroids = [] 
        for clus in range(k):
            #print(clus)
            #print(np.sum(np.abs(row - centroids[clus,:])))
            dist = np.sum(np.abs(arr2D[row] - centroids[clus,:])) # CALCULATE THE DISTANCE
            # 
            heapq.heappush(min_dis_centroids, (dist, clus) )  #make min heap on
                                                     # basis tuple[0]("Cluster distance") index, also store the cluster name
                                                     # to get min cluster and its name easily


        #heapq.heapify(min_dis_centroids)
        #print(min_dis_centroids)
        #print(min_dis_centroids[0][1])
       
        selected_centroid_row[row] = min_dis_centroids[0][1] # min distance value on the zero index,(tuple)[1] for "cluster NO"
    print('iteration',i)
  
    print(centroids)
    print()
    for c in range(k): # 
        
        group_rows = arr2D[selected_centroid_row == c]
        
        centroids[c,:] = np.mean(group_rows,axis=0) # Update the centroids WITH MEAN OF SAME CLUSTER (i.e c1, c2)
print('Finished: ') 
print('final centroids ',centroids)

centroids # Centroids 

# UPDATE The Pixels color finally according to clusteres


for c in range(k):
    arr2D[selected_centroid_row == c] = centroids[c]

arr2D.shape = (arr.shape[0],arr.shape[1],arr.shape[2])


# Arange Shape of Array for image 

arr2D = arr2D.reshape(arr.shape)

cv2.imshow('image',arr2D) # not showing array

# DOWNLOAD THE IMAGE 

cv2.imwrite('img1_k10.jpg', arr2D)













(72600, 3)
[[155. 167. 161.]
 [ 74.  98.  90.]
 [255. 250. 255.]
 [117. 134. 107.]
 [165. 172. 165.]
 [147. 164. 161.]
 [ 63. 106.  73.]
 [ 59.  86.  82.]
 [115. 134. 107.]
 [105. 128. 100.]]
iteration 0
[[155. 167. 161.]
 [ 74.  98.  90.]
 [255. 250. 255.]
 [117. 134. 107.]
 [165. 172. 165.]
 [147. 164. 161.]
 [ 63. 106.  73.]
 [ 59.  86.  82.]
 [115. 134. 107.]
 [105. 128. 100.]]

iteration 1
[[155.57345491 170.73454914 168.60587639]
 [ 79.27634046 100.29490064 101.81477315]
 [227.01615313 224.65583567 229.0875817 ]
 [128.63328424 137.58910162 129.19587629]
 [187.10381125 186.49437387 192.17731397]
 [115.90541655 187.62805884 153.37235359]
 [ 58.54668567 119.33285816  81.67925873]
 [ 50.43094629  52.52393131  60.22506394]
 [ 94.67741329 173.38659648 123.67402951]
 [ 89.66882622 133.27210366 112.14119665]]

iteration 2
[[156.41706161 169.48229718 172.73571229]
 [ 82.54769281  94.68530898 101.55339964]
 [226.39454944 224.2862686  228.82210353]
 [128.01184308 134.08981002 143.79768073]


iteration 19
[[173.78091221 187.14210388 192.23095175]
 [ 86.39496403 114.36388489 106.34561151]
 [230.77948257 228.33286255 231.93971882]
 [145.45630317 157.46274813 166.26965713]
 [212.90413857 212.1598572  219.41372471]
 [113.98651155 197.96509863 144.02773563]
 [ 67.23320994  84.40208003  82.22633527]
 [ 35.70281583  31.20395738  40.82990868]
 [ 86.72476592 176.21586583 119.48842474]
 [112.02945924 131.88256659 139.09443099]]

iteration 20
[[175.43423571 187.79573421 193.37052229]
 [ 86.8681396  115.00478469 106.94202083]
 [230.9357936  228.48837361 232.04644024]
 [147.28871595 160.14967575 166.92970169]
 [213.43334624 212.5622661  219.74280552]
 [113.83233381 197.93909959 144.10228904]
 [ 67.44149766  84.61743803  82.45363148]
 [ 35.70281583  31.20395738  40.82990868]
 [ 86.80390144 176.1674538  119.48398357]
 [113.62765312 132.60319385 141.42672327]]

iteration 21
[[176.95223377 188.4785052  194.82691767]
 [ 87.56527145 115.30846802 107.73380301]
 [231.12042094 228.64373252 232.1

iteration 38
[[193.1660996  197.59727807 207.84967522]
 [ 96.95291637 121.02066058 118.87378777]
 [234.14194787 231.57617701 234.7635886 ]
 [162.17728532 179.97728532 180.9465374 ]
 [220.73079597 218.7987487  224.14529023]
 [113.15698872 197.6127996  143.56469813]
 [ 71.76266771  93.43806174  88.73218705]
 [ 38.9291866   36.04976077  44.69569378]
 [ 86.4382992  175.13390165 118.89032124]
 [132.62542882 145.4191681  157.88036021]]

iteration 39
[[193.61229534 197.91751622 208.09236948]
 [ 97.3449443  121.18474122 119.34832887]
 [234.25981811 231.74483258 234.90109549]
 [162.45190967 180.42068581 181.492891  ]
 [220.94546233 218.94486301 224.27388699]
 [113.12545186 197.58207361 143.5726257 ]
 [ 71.86134021  93.70760309  88.89304124]
 [ 39.03598726  36.08248408  44.71751592]
 [ 86.41131132 175.07759608 118.80918654]
 [133.25708763 145.82195017 158.21005155]]

iteration 40
[[193.84473602 198.17244611 208.42486723]
 [ 97.74620729 121.37402524 119.79101092]
 [234.22678163 231.79098276 234.9

True

### image_1 for 20 k

In [73]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import cv2  # redd and show the image 
import random as r


# to use for image read/write/show processing
#!pip install opencv-python

arr = cv2.imread("baby1_image.jpeg")




arr2D = arr.reshape((arr.shape[0]*arr.shape[1],3)) # 
print(arr2D.shape)



### Initialization of k Centroids

k = 20   # Select centroids from the give image pixels
centroids = np.zeros((k,3))
for i in range(k):
    
    row_idx = r.randint(0,arr.shape[0])
    
    centroids[i,:] = arr2D[row_idx,:]
    
print(centroids)

import heapq  # to store the min distance centroid efficiently 


# 

clusters_arr = np.zeros((arr2D.shape[0],3))

for i in range(50):
    selected_centroid_row = np.zeros(arr2D.shape[0])
    
    for row in range(arr2D.shape[0]):  # CALCULATE THE DISTANCE FOR EACH PIXEL,FROM EACH DISTANCE 
        min_dis_centroids = [] 
        for clus in range(k):
            #print(clus)
            #print(np.sum(np.abs(row - centroids[clus,:])))
            dist = np.sum(np.abs(arr2D[row] - centroids[clus,:])) # CALCULATE THE DISTANCE
            # 
            heapq.heappush(min_dis_centroids, (dist, clus) )  #make min heap on
                                                     # basis tuple[0]("Cluster distance") index, also store the cluster name
                                                     # to get min cluster and its name easily


        #heapq.heapify(min_dis_centroids)
        #print(min_dis_centroids)
        #print(min_dis_centroids[0][1])
       
        selected_centroid_row[row] = min_dis_centroids[0][1] # min distance value on the zero index,(tuple)[1] for "cluster NO"
    print('iteration',i)
  
    print(centroids)
    print()
    for c in range(k): # 
        
        group_rows = arr2D[selected_centroid_row == c]
        
        centroids[c,:] = np.mean(group_rows,axis=0) # Update the centroids WITH MEAN OF SAME CLUSTER (i.e c1, c2)
print('Finished: ') 
print('final centroids ',centroids)

centroids # Centroids 

# UPDATE The Pixels color finally according to clusteres


for c in range(k):
    arr2D[selected_centroid_row == c] = centroids[c]

arr2D.shape = (arr.shape[0],arr.shape[1],arr.shape[2])


# Arange Shape of Array for image 

arr2D = arr2D.reshape(arr.shape)

cv2.imshow('image',arr2D) # not showing array

# DOWNLOAD THE IMAGE 

cv2.imwrite('img1_k20.jpg', arr2D)













(72600, 3)
[[ 70. 114. 107.]
 [ 88. 122. 138.]
 [ 62.  84.  55.]
 [ 77. 100.  96.]
 [ 65.  97.  66.]
 [115. 175. 157.]
 [ 79. 116.  90.]
 [ 57. 102.  69.]
 [115. 134. 107.]
 [ 44.  90.  61.]
 [ 65. 137.  95.]
 [ 81. 106.  96.]
 [249. 255. 250.]
 [ 74. 132.  97.]
 [ 51.  83.  52.]
 [217. 225. 218.]
 [ 50.  98.  70.]
 [ 61.  93.  62.]
 [ 80. 126. 127.]
 [ 96. 118.  93.]]
iteration 0
[[ 70. 114. 107.]
 [ 88. 122. 138.]
 [ 62.  84.  55.]
 [ 77. 100.  96.]
 [ 65.  97.  66.]
 [115. 175. 157.]
 [ 79. 116.  90.]
 [ 57. 102.  69.]
 [115. 134. 107.]
 [ 44.  90.  61.]
 [ 65. 137.  95.]
 [ 81. 106.  96.]
 [249. 255. 250.]
 [ 74. 132.  97.]
 [ 51.  83.  52.]
 [217. 225. 218.]
 [ 50.  98.  70.]
 [ 61.  93.  62.]
 [ 80. 126. 127.]
 [ 96. 118.  93.]]

iteration 1
[[ 69.14446721 107.5829918  112.1147541 ]
 [100.10848508 124.14529252 144.11972104]
 [ 69.76560901  57.01535312  61.63357216]
 [ 80.31373657  87.51130582  98.2736009 ]
 [ 73.79579208  83.81064356  74.98143564]
 [118.83270418 185.75542923 148.

iteration 10
[[ 86.41654711 125.10951698 138.71879484]
 [116.85008977 148.95825853 178.93536804]
 [ 72.840399    39.01745636  41.88029925]
 [ 79.25980181  86.83326153  99.41102973]
 [127.90405904  80.96678967  76.17712177]
 [125.39854318 201.82101977 151.06065111]
 [ 83.29969552 135.17311875  98.36885602]
 [ 70.32136602 107.91637478  91.9614711 ]
 [169.87721729 175.35282705 181.11807095]
 [ 41.44091223  45.45058742  55.74153421]
 [ 71.71988796 169.59558824 109.15686275]
 [103.35344828 110.83512931 113.54274425]
 [229.08606624 226.67923713 230.58609325]
 [ 97.83882149 170.74449121 117.76008913]
 [ 18.6898288   12.02819738  23.40181269]
 [204.34735366 205.67437785 214.43042411]
 [ 61.6300813   67.63821138  82.70615563]
 [ 54.85275424  93.36440678  65.58050847]
 [ 97.68477882 191.84651109 135.82967607]
 [139.70148712 139.81537904 138.77874501]]

iteration 11
[[ 87.7687235  125.84455959 139.94112106]
 [117.57894737 149.85995423 180.56750572]
 [ 72.46551724  38.69458128  41.85221675]
 [ 80.

iteration 20
[[ 97.44818871 132.43176074 148.07708509]
 [124.45190758 156.01504567 189.3057496 ]
 [ 71.72027972  38.86946387  41.96503497]
 [ 83.55664679  91.26201333 102.66152227]
 [131.45054945  82.26007326  78.54212454]
 [130.15763644 203.30408324 153.85492737]
 [ 80.30023781 155.61741974 102.71224732]
 [ 82.31711712 118.07507508 105.203003  ]
 [181.36430462 187.00793884 195.75330785]
 [ 42.80205811  49.98547215  57.41525424]
 [ 81.38529922 181.56808326 124.56960104]
 [119.55568959 121.93124246 123.66143949]
 [231.30489386 228.83243465 232.34844038]
 [108.74457899 175.0495635  126.26077161]
 [ 18.97771318  12.66957364  24.11434109]
 [214.66037967 213.65756277 220.56338028]
 [ 64.07666345  70.82063645  84.32642237]
 [ 61.69359916 104.81951731  78.90503673]
 [103.45470013 196.3865022  139.08677159]
 [160.4807377  152.82704918 153.96393443]]

iteration 21
[[ 98.13261339 133.07991361 148.7425486 ]
 [125.14102564 156.36965812 189.80235043]
 [ 71.612529    38.6450116   41.98607889]
 [ 83.

iteration 30
[[100.29080579 136.45919421 157.3357438 ]
 [129.57001743 160.57989541 194.05984893]
 [ 45.64114462  36.88167053  45.46481052]
 [ 86.93109541  98.66931684 107.80565371]
 [133.89864865  84.99324324  81.0472973 ]
 [134.42600423 204.39059197 157.71564482]
 [ 77.57713301 165.44182706 105.48290721]
 [ 94.42631579 130.04365325 113.09009288]
 [187.8129771  191.59160305 201.22049325]
 [ 52.35329341  64.56069679  67.81709309]
 [ 83.53449446 186.90771319 134.01922642]
 [133.31792657 130.4462203  134.48164147]
 [233.05057194 230.53754193 233.79151974]
 [105.45836233 177.57573649 124.39573185]
 [ 16.21504113  10.16921269  21.37837838]
 [218.56767061 216.96111323 222.93252002]
 [ 69.32595054  80.29198966  87.49649317]
 [ 68.29919137 118.61532538  92.2884097 ]
 [110.52947353 198.27643618 140.95740213]
 [166.98789238 159.79461883 161.30807175]]

iteration 31
[[100.53977273 136.80681818 157.96332645]
 [129.99941246 161.10752056 194.64042303]
 [ 45.7         37.88695652  46.36811594]
 [ 87.

iteration 40
[[104.93079238 139.25977934 164.00902708]
 [134.66115702 166.34011443 197.82517483]
 [ 47.71064061  45.334962    53.01140065]
 [ 92.48545455 105.65393939 115.79878788]
 [142.99667774  90.71428571  87.72757475]
 [132.52653816 205.15790863 157.18325852]
 [ 76.10675717 166.37149028 105.57204566]
 [100.52399573 137.62495556 116.47955919]
 [191.76817349 195.22632865 205.3787416 ]
 [ 59.47392963  76.29843154  75.69775329]
 [ 82.30964171 187.18933877 139.23070201]
 [142.97503174 139.23360135 141.3008887 ]
 [233.48578024 231.01542013 234.26278855]
 [ 99.68323241 181.56274796 122.00960535]
 [ 19.80273438  12.47265625  23.54785156]
 [219.82559425 217.96535839 223.55389718]
 [ 75.53084416  87.64318182  93.76038961]
 [ 73.22963999 123.40964698  97.85354771]
 [112.01088075 196.36906337 140.10939568]
 [173.48390197 168.53676117 169.41182124]]

iteration 41
[[105.51805416 139.71664995 164.99197593]
 [135.94458438 167.62216625 198.45277078]
 [ 48.09860665  45.93515541  53.57717042]
 [ 93.

True

In [74]:
arr = cv2.imread('img2.jpg')


array([[[ 32,  51,  66],
        [ 35,  54,  69],
        [ 39,  58,  73],
        ...,
        [ 20,  38,  45],
        [ 20,  38,  45],
        [ 21,  39,  46]],

       [[ 34,  53,  68],
        [ 36,  55,  70],
        [ 38,  57,  72],
        ...,
        [ 21,  39,  46],
        [ 21,  39,  46],
        [ 22,  40,  47]],

       [[ 36,  55,  70],
        [ 37,  56,  71],
        [ 38,  57,  72],
        ...,
        [ 20,  38,  45],
        [ 21,  39,  46],
        [ 22,  40,  47]],

       ...,

       [[135, 144, 157],
        [134, 143, 156],
        [134, 143, 156],
        ...,
        [ 82,  98, 114],
        [ 80,  96, 112],
        [ 76,  92, 108]],

       [[132, 141, 154],
        [132, 141, 154],
        [132, 141, 154],
        ...,
        [ 80,  96, 112],
        [ 80,  96, 112],
        [ 79,  95, 111]],

       [[134, 143, 156],
        [133, 142, 155],
        [132, 141, 154],
        ...,
        [ 76,  92, 108],
        [ 79,  95, 111],
        [ 82,  98, 114]]

### k means Clustering for  Image 2 

In [77]:
arr.shape

AttributeError: 'NoneType' object has no attribute 'shape'

### img2 k == 3

In [82]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import cv2  # redd and show the image 
import random as r


# to use for image read/write/show processing
#!pip install opencv-python

arr = cv2.imread("img2.jpg")




arr2D = arr.reshape((arr.shape[0]*arr.shape[1],3)) # 
print(arr2D.shape)



### Initialization of k Centroids

k = 3   # Select centroids from the give image pixels
centroids = np.zeros((k,3))
for i in range(k):
    
    row_idx = r.randint(0,arr.shape[0])
    
    centroids[i,:] = arr2D[row_idx,:]
    
print(centroids)

import heapq  # to store the min distance centroid efficiently 


# 

clusters_arr = np.zeros((arr2D.shape[0],3))

for i in range(50):
    selected_centroid_row = np.zeros(arr2D.shape[0])
    
    for row in range(arr2D.shape[0]):  # CALCULATE THE DISTANCE FOR EACH PIXEL,FROM EACH DISTANCE 
        min_dis_centroids = [] 
        for clus in range(k):
            #print(clus)
            #print(np.sum(np.abs(row - centroids[clus,:])))
            dist = np.sum(np.abs(arr2D[row] - centroids[clus,:])) # CALCULATE THE DISTANCE
            # 
            heapq.heappush(min_dis_centroids, (dist, clus) )  #make min heap on
                                                     # basis tuple[0]("Cluster distance") index, also store the cluster name
                                                     # to get min cluster and its name easily


        #heapq.heapify(min_dis_centroids)
        #print(min_dis_centroids)
        #print(min_dis_centroids[0][1])
       
        selected_centroid_row[row] = min_dis_centroids[0][1] # min distance value on the zero index,(tuple)[1] for "cluster NO"
    print('iteration',i)
  
    print(centroids)
    print()
    for c in range(k): # 
        
        group_rows = arr2D[selected_centroid_row == c]
        
        centroids[c,:] = np.mean(group_rows,axis=0) # Update the centroids WITH MEAN OF SAME CLUSTER (i.e c1, c2)
print('Finished: ') 
print('final centroids ',centroids)

centroids # Centroids 

# UPDATE The Pixels color finally according to clusteres


for c in range(k):
    arr2D[selected_centroid_row == c] = centroids[c]

arr2D.shape = (arr.shape[0],arr.shape[1],arr.shape[2])


# Arange Shape of Array for image 

arr2D = arr2D.reshape(arr.shape)

cv2.imshow('image',arr2D) # not showing array

# DOWNLOAD THE IMAGE 

cv2.imwrite('img2_k3.jpg', arr2D)













(15000, 3)
[[  0. 104. 171.]
 [165. 168. 166.]
 [177. 185. 185.]]
iteration 0
[[  0. 104. 171.]
 [165. 168. 166.]
 [177. 185. 185.]]

iteration 1
[[ 25.00169469 105.06557163 156.93703559]
 [122.64184075 147.96033909 179.53739025]
 [182.55489319 208.78216592 222.79905614]]

iteration 2
[[ 22.58255173  95.90323061 147.72681257]
 [116.08140442 146.47646294 182.61664499]
 [165.34925642 209.06804867 225.19671023]]

iteration 3
[[ 22.53475224  86.83189225 138.12238111]
 [112.20879979 143.5988024  179.98802395]
 [148.75063168 206.30864917 227.76734694]]

iteration 4
[[ 22.00539635  79.71269073 130.19017492]
 [102.9886195  140.98688768 177.56209797]
 [142.78348854 203.6144341  228.60261461]]

iteration 5
[[ 20.40826512  77.01217808 126.88460771]
 [ 97.11688931 137.6245229  175.67724237]
 [141.83497155 202.19899983 227.94637006]]

iteration 6
[[ 20.35387631  73.26350174 121.98279617]
 [ 88.81832437 134.95945341 175.54547491]
 [141.63694482 201.26901077 227.13408479]]

iteration 7
[[ 20.57187727

True

In [83]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import cv2  # redd and show the image 
import random as r


# to use for image read/write/show processing
#!pip install opencv-python

arr = cv2.imread("img2.jpg")




arr2D = arr.reshape((arr.shape[0]*arr.shape[1],3)) # 
print(arr2D.shape)



### Initialization of k Centroids

k = 10   # Select centroids from the give image pixels
centroids = np.zeros((k,3))
for i in range(k):
    
    row_idx = r.randint(0,arr.shape[0])
    
    centroids[i,:] = arr2D[row_idx,:]
    
print(centroids)

import heapq  # to store the min distance centroid efficiently 


# 

clusters_arr = np.zeros((arr2D.shape[0],3))

for i in range(50):
    selected_centroid_row = np.zeros(arr2D.shape[0])
    
    for row in range(arr2D.shape[0]):  # CALCULATE THE DISTANCE FOR EACH PIXEL,FROM EACH DISTANCE 
        min_dis_centroids = [] 
        for clus in range(k):
            #print(clus)
            #print(np.sum(np.abs(row - centroids[clus,:])))
            dist = np.sum(np.abs(arr2D[row] - centroids[clus,:])) # CALCULATE THE DISTANCE
            # 
            heapq.heappush(min_dis_centroids, (dist, clus) )  #make min heap on
                                                     # basis tuple[0]("Cluster distance") index, also store the cluster name
                                                     # to get min cluster and its name easily


        #heapq.heapify(min_dis_centroids)
        #print(min_dis_centroids)
        #print(min_dis_centroids[0][1])
       
        selected_centroid_row[row] = min_dis_centroids[0][1] # min distance value on the zero index,(tuple)[1] for "cluster NO"
    print('iteration',i)
  
    print(centroids)
    print()
    for c in range(k): # 
        
        group_rows = arr2D[selected_centroid_row == c]
        
        centroids[c,:] = np.mean(group_rows,axis=0) # Update the centroids WITH MEAN OF SAME CLUSTER (i.e c1, c2)
print('Finished: ') 
print('final centroids ',centroids)

centroids # Centroids 

# UPDATE The Pixels color finally according to clusteres


for c in range(k):
    arr2D[selected_centroid_row == c] = centroids[c]

arr2D.shape = (arr.shape[0],arr.shape[1],arr.shape[2])


# Arange Shape of Array for image 

arr2D = arr2D.reshape(arr.shape)

cv2.imshow('image',arr2D) # not showing array

# DOWNLOAD THE IMAGE 

cv2.imwrite('img2_k10.jpg', arr2D)













(15000, 3)
[[176. 184. 183.]
 [  0.  68. 116.]
 [  2. 103. 158.]
 [171. 171. 177.]
 [ 13.  77. 108.]
 [ 16.  76. 106.]
 [  6.  60.  93.]
 [  6.  60.  93.]
 [176. 181. 182.]
 [  0. 122. 190.]]
iteration 0
[[176. 184. 183.]
 [  0.  68. 116.]
 [  2. 103. 158.]
 [171. 171. 177.]
 [ 13.  77. 108.]
 [ 16.  76. 106.]
 [  6.  60.  93.]
 [  6.  60.  93.]
 [176. 181. 182.]
 [  0. 122. 190.]]

iteration 1
[[189.46569179 212.69347582 222.01406074]
 [  4.81637168  62.66482301 126.15707965]
 [ 42.41407223  99.30323786 156.36674969]
 [126.86933979 152.63014172 185.65779468]
 [ 53.12711864  90.8220339  122.74067797]
 [ 65.07914764  84.21613394  99.13089802]
 [ 15.56769374  36.11391223  55.00093371]
 [         nan          nan          nan]
 [145.62416107 179.10402685 218.95637584]
 [ 24.64963504 151.89343066 216.17605839]]

iteration 2
[[208.18021892 219.82173573 213.28381548]
 [  7.0472155   65.53510896 126.07082324]
 [ 34.95427902 101.5855803  169.73094959]
 [120.51310564 143.88006354 175.31612391]


iteration 19
[[221.96480447 224.7150838  200.79273743]
 [ 11.66280148  69.48886827 128.4364564 ]
 [ 20.16762178 115.71728749 188.7574021 ]
 [122.74215886 151.99633401 188.54786151]
 [ 96.59054545 118.91272727 146.776     ]
 [ 71.50658858  83.08052709  87.05124451]
 [ 11.45958084  24.85329341  37.8742515 ]
 [         nan          nan          nan]
 [153.61058924 193.48975235 238.93467122]
 [ 11.65831594 193.25191371 245.81489214]]

iteration 20
[[222.00894855 224.71979866 200.76454139]
 [ 11.73172988  69.53145236 128.37881591]
 [ 20.13999044 115.7118968  188.75059723]
 [122.76759411 152.07937807 188.70417349]
 [ 96.87246377 119.1557971  147.09275362]
 [ 71.98245614  83.36549708  87.29532164]
 [ 11.53213752  24.9058296   37.83856502]
 [         nan          nan          nan]
 [153.62313274 193.51813914 238.94451558]
 [ 11.65831594 193.25191371 245.81489214]]

iteration 21
[[222.08754209 224.74466891 200.6043771 ]
 [ 11.77736721  69.54457275 128.37090069]
 [ 20.12141491 115.69933078 188.7

iteration 38
[[222.27627119 224.77627119 200.3740113 ]
 [ 12.03400735  69.45082721 127.93152574]
 [ 18.83504148 115.57003416 188.50073206]
 [124.67541557 154.48818898 190.90901137]
 [ 97.99404368 122.93712773 156.9060225 ]
 [ 78.06282051  89.90897436  95.47307692]
 [ 14.07746479  26.86338028  37.77464789]
 [         nan          nan          nan]
 [154.69689006 194.47919404 239.60840999]
 [ 11.49686411 193.26132404 245.83135889]]

iteration 39
[[222.31052036 224.78506787 200.33936652]
 [ 12.10567246  69.4684355  127.88792315]
 [ 18.72860636 115.54865526 188.44547677]
 [124.92104102 154.77547419 191.15174239]
 [ 98.21166448 123.39908257 157.83813893]
 [ 78.52604828  90.3545108   96.05082592]
 [ 14.34647887  26.98169014  37.61408451]
 [         nan          nan          nan]
 [154.79938543 194.56233538 239.65057068]
 [ 11.4068388  193.29448709 245.85275645]]

iteration 40
[[222.39364719 224.765173   200.19171866]
 [ 12.15992647  69.35569853 127.74862132]
 [ 18.64720195 115.43357664 188.3

True

In [84]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import cv2  # redd and show the image 
import random as r


# to use for image read/write/show processing
#!pip install opencv-python

arr = cv2.imread("img2.jpg")




arr2D = arr.reshape((arr.shape[0]*arr.shape[1],3)) # 
print(arr2D.shape)



### Initialization of k Centroids

k = 20   # Select centroids from the give image pixels
centroids = np.zeros((k,3))
for i in range(k):
    
    row_idx = r.randint(0,arr.shape[0])
    
    centroids[i,:] = arr2D[row_idx,:]
    
print(centroids)

import heapq  # to store the min distance centroid efficiently 


# 

clusters_arr = np.zeros((arr2D.shape[0],3))

for i in range(50):
    selected_centroid_row = np.zeros(arr2D.shape[0])
    
    for row in range(arr2D.shape[0]):  # CALCULATE THE DISTANCE FOR EACH PIXEL,FROM EACH DISTANCE 
        min_dis_centroids = [] 
        for clus in range(k):
            #print(clus)
            #print(np.sum(np.abs(row - centroids[clus,:])))
            dist = np.sum(np.abs(arr2D[row] - centroids[clus,:])) # CALCULATE THE DISTANCE
            # 
            heapq.heappush(min_dis_centroids, (dist, clus) )  #make min heap on
                                                     # basis tuple[0]("Cluster distance") index, also store the cluster name
                                                     # to get min cluster and its name easily


        #heapq.heapify(min_dis_centroids)
        #print(min_dis_centroids)
        #print(min_dis_centroids[0][1])
       
        selected_centroid_row[row] = min_dis_centroids[0][1] # min distance value on the zero index,(tuple)[1] for "cluster NO"
    print('iteration',i)
  
    print(centroids)
    print()
    for c in range(k): # 
        
        group_rows = arr2D[selected_centroid_row == c]
        
        centroids[c,:] = np.mean(group_rows,axis=0) # Update the centroids WITH MEAN OF SAME CLUSTER (i.e c1, c2)
print('Finished: ') 
print('final centroids ',centroids)

centroids # Centroids 

# UPDATE The Pixels color finally according to clusteres


for c in range(k):
    arr2D[selected_centroid_row == c] = centroids[c]

arr2D.shape = (arr.shape[0],arr.shape[1],arr.shape[2])


# Arange Shape of Array for image 

arr2D = arr2D.reshape(arr.shape)

cv2.imshow('image',arr2D) # not showing array

# DOWNLOAD THE IMAGE 

cv2.imwrite('img2_k20.jpg', arr2D)













(15000, 3)
[[ 66.  85.  90.]
 [  4. 111. 169.]
 [  0. 121. 192.]
 [177. 185. 184.]
 [  7. 115. 179.]
 [168. 168. 168.]
 [152. 157. 166.]
 [  0.  61. 100.]
 [  6. 113. 174.]
 [177. 185. 185.]
 [  0. 120. 190.]
 [179. 187. 187.]
 [  8. 115. 182.]
 [ 32.  65.  80.]
 [177. 185. 184.]
 [  0. 121. 191.]
 [  7. 115. 179.]
 [  1.  97. 150.]
 [  4. 117. 184.]
 [167. 166. 168.]]
iteration 0
[[ 66.  85.  90.]
 [  4. 111. 169.]
 [  0. 121. 192.]
 [177. 185. 184.]
 [  7. 115. 179.]
 [168. 168. 168.]
 [152. 157. 166.]
 [  0.  61. 100.]
 [  6. 113. 174.]
 [177. 185. 185.]
 [  0. 120. 190.]
 [179. 187. 187.]
 [  8. 115. 182.]
 [ 32.  65.  80.]
 [177. 185. 184.]
 [  0. 121. 191.]
 [  7. 115. 179.]
 [  1.  97. 150.]
 [  4. 117. 184.]
 [167. 166. 168.]]

iteration 1
[[ 83.15276382  96.65226131 104.30452261]
 [ 33.43467337 101.39698492 165.8919598 ]
 [ 18.15716096 166.89987326 228.27249683]
 [186.         183.25842697 133.20224719]
 [ 38.06586826 108.19161677 178.46107784]
 [171.30081301 173.04878049 146.

iteration 10
[[ 96.70310391 107.69905533 115.27530364]
 [ 39.01342282  83.32885906 128.61912752]
 [  9.98399326 199.37320977 250.10362258]
 [225.81065089 216.89201183 165.63017751]
 [ 80.54696133 125.89364641 190.69337017]
 [155.6350211  167.49156118 171.48523207]
 [124.46989051 139.52281022 155.75091241]
 [  6.31494253  15.4183908   24.18850575]
 [ 47.87883959  98.15699659 171.93856655]
 [153.03902954 192.88291139 240.28164557]
 [  3.77819549 118.25845865 189.72368421]
 [215.87646528 235.18214608 248.54102795]
 [111.54868624 157.19783617 218.30602782]
 [ 55.50492611  63.72167488  59.88916256]
 [         nan          nan          nan]
 [ 18.98938429 152.56900212 218.38853503]
 [         nan          nan          nan]
 [  5.55827703  56.86317568 111.30152027]
 [  6.47263682  82.93656716 151.06716418]
 [202.04280156 184.04669261  99.79766537]]

iteration 11
[[ 96.40841248 107.4192673  115.04477612]
 [ 39.046875    83.19270833 127.33680556]
 [  9.93591906 199.39376054 250.11045531]
 [225.

iteration 20
[[100.08497724 110.50834598 117.19878604]
 [ 55.81896552  85.7887931  109.37068966]
 [  9.93591906 199.38701518 250.13322091]
 [225.84272997 217.30712166 166.72700297]
 [ 89.15528634 135.04955947 199.76762115]
 [153.97991968 165.56024096 171.21285141]
 [124.08492366 139.22709924 155.52003817]
 [  4.48108108  12.09459459  19.02432432]
 [ 53.56216216 102.33243243 172.19324324]
 [158.73687316 197.8979351  241.86489676]
 [  3.71379898 116.23424191 186.84241908]
 [219.94382022 237.45863126 249.48008172]
 [120.8640625  165.6390625  224.62421875]
 [ 51.49719101  58.32022472  51.08988764]
 [         nan          nan          nan]
 [ 18.40748441 151.74844075 218.0997921 ]
 [         nan          nan          nan]
 [  5.41835749  54.14299517 106.79323671]
 [ 12.90747029  77.61714771 144.17996604]
 [202.04363636 184.96       102.57454545]]

iteration 21
[[100.71538462 111.12       117.61230769]
 [ 58.38074398  86.09846827 107.14660832]
 [  9.93591906 199.38701518 250.13322091]
 [225.

iteration 30
[[100.85543964 112.29210134 119.34873323]
 [ 62.50436681  84.69432314 102.19432314]
 [  9.93591906 199.38701518 250.13322091]
 [225.84272997 217.30712166 166.72700297]
 [ 89.53516484 135.38021978 200.04285714]
 [154.35185185 165.97942387 171.47530864]
 [124.73046875 139.89941406 156.38867188]
 [  4.04683196  11.64187328  18.75757576]
 [ 54.11584554 102.43009321 171.48069241]
 [159.04451039 198.12522255 241.92522255]
 [  3.96717172 115.81313131 186.57996633]
 [220.1336074  237.57656732 249.5323741 ]
 [121.14341387 166.00155885 224.89321902]
 [ 48.740625    55.75        47.628125  ]
 [         nan          nan          nan]
 [ 18.29652352 151.40490798 217.95501022]
 [         nan          nan          nan]
 [  5.50146915  53.97453477 106.42409403]
 [ 13.81174578  77.60579244 142.81094127]
 [202.04363636 184.96       102.57454545]]

iteration 31
[[100.85543964 112.29210134 119.34873323]
 [ 62.50436681  84.69432314 102.19432314]
 [  9.93591906 199.38701518 250.13322091]
 [225.

iteration 40
[[100.85543964 112.29210134 119.34873323]
 [ 62.50436681  84.69432314 102.19432314]
 [  9.93591906 199.38701518 250.13322091]
 [225.84272997 217.30712166 166.72700297]
 [ 89.53516484 135.38021978 200.04285714]
 [154.35185185 165.97942387 171.47530864]
 [124.73046875 139.89941406 156.38867188]
 [  4.04683196  11.64187328  18.75757576]
 [ 54.11584554 102.43009321 171.48069241]
 [159.04451039 198.12522255 241.92522255]
 [  3.96717172 115.81313131 186.57996633]
 [220.1336074  237.57656732 249.5323741 ]
 [121.14341387 166.00155885 224.89321902]
 [ 48.740625    55.75        47.628125  ]
 [         nan          nan          nan]
 [ 18.29652352 151.40490798 217.95501022]
 [         nan          nan          nan]
 [  5.50146915  53.97453477 106.42409403]
 [ 13.81174578  77.60579244 142.81094127]
 [202.04363636 184.96       102.57454545]]

iteration 41
[[100.85543964 112.29210134 119.34873323]
 [ 62.50436681  84.69432314 102.19432314]
 [  9.93591906 199.38701518 250.13322091]
 [225.

True

In [91]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import cv2  # redd and show the image 
import random as r


# to use for image read/write/show processing
#!pip install opencv-python

arr = cv2.imread("img2.jpg")




arr2D = arr.reshape((arr.shape[0]*arr.shape[1],3)) # 
print(arr2D.shape)



### Initialization of k Centroids

k = 40   # Select centroids from the give image pixels
centroids = np.zeros((k,3))
for i in range(k):
    
    row_idx = r.randint(0,arr.shape[0])
    
    centroids[i,:] = arr2D[row_idx,:]
    
print(centroids)

import heapq  # to store the min distance centroid efficiently 


# 

clusters_arr = np.zeros((arr2D.shape[0],3))

for i in range(50):
    selected_centroid_row = np.zeros(arr2D.shape[0])
    
    for row in range(arr2D.shape[0]):  # CALCULATE THE DISTANCE FOR EACH PIXEL,FROM EACH DISTANCE 
        min_dis_centroids = [] 
        for clus in range(k):
            #print(clus)
            #print(np.sum(np.abs(row - centroids[clus,:])))
            dist = np.sum(np.abs(arr2D[row] - centroids[clus,:])) # CALCULATE THE DISTANCE
            # 
            heapq.heappush(min_dis_centroids, (dist, clus) )  #make min heap on
                                                     # basis tuple[0]("Cluster distance") index, also store the cluster name
                                                     # to get min cluster and its name easily


        #heapq.heapify(min_dis_centroids)
        #print(min_dis_centroids)
        #print(min_dis_centroids[0][1])
       
        selected_centroid_row[row] = min_dis_centroids[0][1] # min distance value on the zero index,(tuple)[1] for "cluster NO"
    print('iteration',i)
  
    print(centroids)
    print()
    for c in range(k): # 
        
        group_rows = arr2D[selected_centroid_row == c]
        
        centroids[c,:] = np.mean(group_rows,axis=0) # Update the centroids WITH MEAN OF SAME CLUSTER (i.e c1, c2)
print('Finished: ') 
print('final centroids ',centroids)

centroids # Centroids 

# UPDATE The Pixels color finally according to clusteres


for c in range(k):
    arr2D[selected_centroid_row == c] = centroids[c]

arr2D.shape = (arr.shape[0],arr.shape[1],arr.shape[2])


# Arange Shape of Array for image 

arr2D = arr2D.reshape(arr.shape)

cv2.imshow('image',arr2D) # not showing array

# DOWNLOAD THE IMAGE 

cv2.imwrite('img2_k40.jpg', arr2D)













(15000, 3)
[[182. 181. 190.]
 [  6. 120. 183.]
 [163. 166. 174.]
 [  4. 111. 169.]
 [  1.  93. 152.]
 [171. 171. 177.]
 [  0. 121. 191.]
 [  9.  72. 106.]
 [  0. 120. 191.]
 [  0. 121. 190.]
 [185. 183. 189.]
 [167. 166. 168.]
 [  0. 121. 191.]
 [175. 178. 182.]
 [  8. 115. 182.]
 [  0. 122. 190.]
 [171. 171. 177.]
 [  0. 104. 171.]
 [  0.  67. 106.]
 [ 29.  76. 104.]
 [  8. 115. 182.]
 [172. 175. 179.]
 [  0.  61. 100.]
 [165. 168. 166.]
 [  0. 121. 190.]
 [  0. 120. 191.]
 [171. 171. 177.]
 [  4. 117. 184.]
 [  3. 119. 184.]
 [  0. 120. 190.]
 [  0. 122. 190.]
 [100. 111. 131.]
 [176. 184. 183.]
 [  5. 112. 173.]
 [ 13.  77. 108.]
 [184. 182. 188.]
 [  0. 118. 187.]
 [  4.  85. 130.]
 [  0. 118. 187.]
 [  7. 115. 179.]]
iteration 0
[[182. 181. 190.]
 [  6. 120. 183.]
 [163. 166. 174.]
 [  4. 111. 169.]
 [  1.  93. 152.]
 [171. 171. 177.]
 [  0. 121. 191.]
 [  9.  72. 106.]
 [  0. 120. 191.]
 [  0. 121. 190.]
 [185. 183. 189.]
 [167. 166. 168.]
 [  0. 121. 191.]
 [175. 178. 182.]
 [  

iteration 5
[[157.57902098 191.15664336 240.45034965]
 [ 80.18117647 137.61411765 205.03764706]
 [110.22374429 148.68949772 208.95738204]
 [ 19.58947368 113.44210526 131.70526316]
 [ 39.13114754  82.31615925 134.04683841]
 [162.84569733 173.97922849 171.17210682]
 [  8.73871528 199.84114583 250.39149306]
 [ 21.18611987  64.05047319  99.60567823]
 [ 35.54216867 121.25903614 203.94578313]
 [  1.84496124 125.42054264 195.15116279]
 [226.76356192 238.22620266 237.90583419]
 [157.78625954 146.05343511  88.12977099]
 [         nan          nan          nan]
 [141.77633712 175.51539708 229.66288493]
 [ 76.39108911 117.40841584 181.11881188]
 [ 12.64690027 156.393531   220.2425876 ]
 [         nan          nan          nan]
 [ 20.04522613  81.59798995 175.08040201]
 [  2.44525547  47.54014599 104.86277372]
 [ 70.2966805   77.13278008  75.9626556 ]
 [         nan          nan          nan]
 [110.75080386 171.19614148 231.73633441]
 [ 10.98056156  18.3887689   22.06047516]
 [128.98538012 143.511

iteration 10
[[155.75075988 191.80040527 240.76899696]
 [ 93.57692308 140.15961538 205.29423077]
 [115.85335689 155.2385159  214.25441696]
 [ 20.02105263 106.84210526 128.27368421]
 [ 40.17672414  82.30818966 132.04525862]
 [158.86146096 169.81108312 170.40806045]
 [  6.63981481 200.50648148 250.91944444]
 [ 35.69758065  58.10887097  72.00403226]
 [ 49.671875   132.51953125 207.765625  ]
 [  2.38954469 125.61382799 195.38954469]
 [227.57142857 241.79030144 249.91480996]
 [200.64186047 181.35348837  93.62790698]
 [         nan          nan          nan]
 [134.31120332 171.90041494 229.06500692]
 [ 81.96428571 121.78021978 181.92032967]
 [ 10.39265537 159.74576271 222.41525424]
 [         nan          nan          nan]
 [ 16.51538462  77.52692308 168.58846154]
 [  2.97494781  42.82463466  92.58037578]
 [ 73.35962145  77.52050473  70.48895899]
 [         nan          nan          nan]
 [ 88.0472973  186.33783784 241.09797297]
 [  8.84438776  14.80357143  16.9872449 ]
 [126.7945845  141.23

iteration 15
[[156.42588727 192.07724426 240.66283925]
 [ 98.22156863 140.53921569 204.33137255]
 [115.31389365 157.5077187  216.76500858]
 [ 19.96875    107.21875    128.70833333]
 [ 42.08312343  82.62720403 128.38287154]
 [155.39569892 166.71612903 170.75698925]
 [  6.47703843 200.63917526 251.04498594]
 [ 44.43884892  52.10791367  45.57913669]
 [ 50.55241935 137.70564516 211.17741935]
 [  2.98410405 124.39306358 195.05635838]
 [227.52673797 242.02005348 250.80614973]
 [202.24907063 184.78438662 101.60223048]
 [         nan          nan          nan]
 [134.73537604 172.97632312 230.22841226]
 [ 80.11031175 121.78417266 185.9088729 ]
 [  9.26011561 161.02023121 223.09248555]
 [         nan          nan          nan]
 [ 11.22274882  75.79146919 170.27488152]
 [  4.15437788  42.47004608  88.83870968]
 [ 76.15229885  83.43103448  85.54597701]
 [         nan          nan          nan]
 [ 86.68164794 190.         243.14981273]
 [  3.51818182   9.91515152  15.56060606]
 [125.43854474 140.27

iteration 20
[[156.79600421 192.40483701 240.83806519]
 [ 99.00787402 140.89173228 204.53149606]
 [115.76672384 157.90394511 217.24699828]
 [ 20.09677419 107.93548387 128.91397849]
 [ 41.81418093  82.69682152 128.83129584]
 [155.31896552 166.67025862 170.78663793]
 [  6.4840824  200.62078652 251.03277154]
 [ 45.28928571  52.44642857  45.10714286]
 [ 49.13973799 140.63318777 212.83406114]
 [  2.8219697  122.48611111 194.0479798 ]
 [227.61610738 242.08590604 250.81744966]
 [202.15498155 184.83394834 101.99261993]
 [         nan          nan          nan]
 [135.33980583 173.39667129 230.3925104 ]
 [ 79.54504505 122.45495495 187.62162162]
 [  8.64411765 160.92352941 223.08235294]
 [         nan          nan          nan]
 [ 12.25471698  75.83962264 170.11320755]
 [  4.0078125   41.12239583  85.82291667]
 [ 77.37465565  84.61707989  87.26997245]
 [         nan          nan          nan]
 [ 86.80970149 190.08955224 243.1641791 ]
 [  3.56923077   9.71384615  14.98769231]
 [125.82020202 140.68

iteration 25
[[156.79600421 192.40483701 240.83806519]
 [ 99.1765873  141.06944444 204.58531746]
 [115.97800338 158.04230118 217.37563452]
 [ 19.75       107.73958333 129.48958333]
 [ 41.41831683  82.53217822 128.90841584]
 [155.31896552 166.67025862 170.78663793]
 [  6.4840824  200.62078652 251.03277154]
 [ 45.69824561  52.85614035  45.62105263]
 [ 49.1938326  141.40969163 213.04405286]
 [  2.74880383 121.5        193.40669856]
 [227.61610738 242.08590604 250.81744966]
 [202.15498155 184.83394834 101.99261993]
 [         nan          nan          nan]
 [135.44725738 173.53586498 230.49085795]
 [ 79.99553571 122.53125    187.63616071]
 [  8.41107872 160.64723032 222.89504373]
 [         nan          nan          nan]
 [ 13.65178571  76.73660714 170.41964286]
 [  3.85828877  40.73529412  85.14438503]
 [ 78.17808219  85.28219178  87.7260274 ]
 [         nan          nan          nan]
 [ 86.80970149 190.08955224 243.1641791 ]
 [  3.69753086   9.66049383  14.75      ]
 [125.85526316 140.69

iteration 30
[[156.79600421 192.40483701 240.83806519]
 [ 99.28830645 141.2358871  204.75201613]
 [115.97800338 158.04230118 217.37563452]
 [ 20.29787234 107.31914894 129.05319149]
 [ 41.35555556  82.5308642  128.91111111]
 [155.31896552 166.67025862 170.78663793]
 [  6.4840824  200.62078652 251.03277154]
 [ 45.69824561  52.85614035  45.62105263]
 [ 49.26637555 141.22270742 212.95196507]
 [  2.72738095 121.23690476 193.2702381 ]
 [227.61610738 242.08590604 250.81744966]
 [202.15498155 184.83394834 101.99261993]
 [         nan          nan          nan]
 [135.44725738 173.53586498 230.49085795]
 [ 80.88154897 123.06605923 187.60136674]
 [  8.34870317 160.53602305 222.63112392]
 [         nan          nan          nan]
 [ 13.99586777  78.42975207 171.61570248]
 [  3.85828877  40.73529412  85.14438503]
 [ 78.17808219  85.28219178  87.7260274 ]
 [         nan          nan          nan]
 [ 86.80970149 190.08955224 243.1641791 ]
 [  3.69753086   9.66049383  14.75      ]
 [125.85526316 140.69

iteration 35
[[156.79600421 192.40483701 240.83806519]
 [ 99.30566802 141.27125506 204.84412955]
 [116.07614213 158.03553299 217.3891709 ]
 [ 20.29787234 107.31914894 129.05319149]
 [ 41.41191067  82.54590571 128.79900744]
 [155.31896552 166.67025862 170.78663793]
 [  6.4840824  200.62078652 251.03277154]
 [ 45.69824561  52.85614035  45.62105263]
 [ 49.25550661 141.34801762 213.17621145]
 [  2.75890736 121.18408551 193.28028504]
 [227.61610738 242.08590604 250.81744966]
 [202.15498155 184.83394834 101.99261993]
 [         nan          nan          nan]
 [135.44507042 173.55352113 230.50704225]
 [ 81.08863636 123.29090909 187.53636364]
 [  8.34870317 160.53602305 222.63112392]
 [         nan          nan          nan]
 [ 14.4691358   79.00411523 171.86419753]
 [  3.85828877  40.73529412  85.14438503]
 [ 78.17808219  85.28219178  87.7260274 ]
 [         nan          nan          nan]
 [ 86.80970149 190.08955224 243.1641791 ]
 [  3.69753086   9.66049383  14.75      ]
 [125.8804458  140.71

iteration 40
[[156.79600421 192.40483701 240.83806519]
 [ 99.30566802 141.27125506 204.84412955]
 [116.07614213 158.03553299 217.3891709 ]
 [ 20.29787234 107.31914894 129.05319149]
 [ 41.41191067  82.54590571 128.79900744]
 [155.31896552 166.67025862 170.78663793]
 [  6.4840824  200.62078652 251.03277154]
 [ 45.69824561  52.85614035  45.62105263]
 [ 49.25550661 141.34801762 213.17621145]
 [  2.75890736 121.18408551 193.28028504]
 [227.61610738 242.08590604 250.81744966]
 [202.15498155 184.83394834 101.99261993]
 [         nan          nan          nan]
 [135.44507042 173.55352113 230.50704225]
 [ 81.08863636 123.29090909 187.53636364]
 [  8.34870317 160.53602305 222.63112392]
 [         nan          nan          nan]
 [ 14.4691358   79.00411523 171.86419753]
 [  3.85828877  40.73529412  85.14438503]
 [ 78.17808219  85.28219178  87.7260274 ]
 [         nan          nan          nan]
 [ 86.80970149 190.08955224 243.1641791 ]
 [  3.69753086   9.66049383  14.75      ]
 [125.8804458  140.71

iteration 45
[[156.79600421 192.40483701 240.83806519]
 [ 99.30566802 141.27125506 204.84412955]
 [116.07614213 158.03553299 217.3891709 ]
 [ 20.29787234 107.31914894 129.05319149]
 [ 41.41191067  82.54590571 128.79900744]
 [155.31896552 166.67025862 170.78663793]
 [  6.4840824  200.62078652 251.03277154]
 [ 45.69824561  52.85614035  45.62105263]
 [ 49.25550661 141.34801762 213.17621145]
 [  2.75890736 121.18408551 193.28028504]
 [227.61610738 242.08590604 250.81744966]
 [202.15498155 184.83394834 101.99261993]
 [         nan          nan          nan]
 [135.44507042 173.55352113 230.50704225]
 [ 81.08863636 123.29090909 187.53636364]
 [  8.34870317 160.53602305 222.63112392]
 [         nan          nan          nan]
 [ 14.4691358   79.00411523 171.86419753]
 [  3.85828877  40.73529412  85.14438503]
 [ 78.17808219  85.28219178  87.7260274 ]
 [         nan          nan          nan]
 [ 86.80970149 190.08955224 243.1641791 ]
 [  3.69753086   9.66049383  14.75      ]
 [125.8804458  140.71

True

### img3 K means algorithm


### img3 k = 3 

In [87]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import cv2  # redd and show the image 
import random as r


# to use for image read/write/show processing
#!pip install opencv-python

arr = cv2.imread("img3.jpg")




arr2D = arr.reshape((arr.shape[0]*arr.shape[1],3)) # 
print(arr2D.shape)



### Initialization of k Centroids

k = 3   # Select centroids from the give image pixels
centroids = np.zeros((k,3))
for i in range(k):
    
    row_idx = r.randint(0,arr.shape[0])
    
    centroids[i,:] = arr2D[row_idx,:]
    
print(centroids)

import heapq  # to store the min distance centroid efficiently 


# 

clusters_arr = np.zeros((arr2D.shape[0],3))

for i in range(50):
    selected_centroid_row = np.zeros(arr2D.shape[0])
    
    for row in range(arr2D.shape[0]):  # CALCULATE THE DISTANCE FOR EACH PIXEL,FROM EACH DISTANCE 
        min_dis_centroids = [] 
        for clus in range(k):
            #print(clus)
            #print(np.sum(np.abs(row - centroids[clus,:])))
            dist = np.sum(np.abs(arr2D[row] - centroids[clus,:])) # CALCULATE THE DISTANCE
            # 
            heapq.heappush(min_dis_centroids, (dist, clus) )  #make min heap on
                                                     # basis tuple[0]("Cluster distance") index, also store the cluster name
                                                     # to get min cluster and its name easily


        #heapq.heapify(min_dis_centroids)
        #print(min_dis_centroids)
        #print(min_dis_centroids[0][1])
       
        selected_centroid_row[row] = min_dis_centroids[0][1] # min distance value on the zero index,(tuple)[1] for "cluster NO"
    print('iteration',i)
  
    print(centroids)
    print()
    for c in range(k): # 
        
        group_rows = arr2D[selected_centroid_row == c]
        
        centroids[c,:] = np.mean(group_rows,axis=0) # Update the centroids WITH MEAN OF SAME CLUSTER (i.e c1, c2)
print('Finished: ') 
print('final centroids ',centroids)

centroids # Centroids 

# UPDATE The Pixels color finally according to clusteres


for c in range(k):
    arr2D[selected_centroid_row == c] = centroids[c]

arr2D.shape = (arr.shape[0],arr.shape[1],arr.shape[2])


# Arange Shape of Array for image 

arr2D = arr2D.reshape(arr.shape)

cv2.imshow('image',arr2D) # not showing array

# DOWNLOAD THE IMAGE 

cv2.imwrite('img3_k3.jpg', arr2D)













(10000, 3)
[[ 21. 150. 253.]
 [  7. 151. 255.]
 [ 37. 139. 255.]]
iteration 0
[[ 21. 150. 253.]
 [  7. 151. 255.]
 [ 37. 139. 255.]]

iteration 1
[[ 18.39524124 140.25974884 248.4064772 ]
 [  5.43088179 152.01848286 235.8090104 ]
 [182.29711375 189.91731749 235.49932088]]

iteration 2
[[ 19.73501905 121.36924143 251.20401801]
 [  7.99836245 178.46834061 222.61954148]
 [197.69702708 198.49857981 235.232153  ]]

iteration 3
[[ 19.16638866  93.58965805 248.93411176]
 [ 12.98442105 194.98147368 230.64547368]
 [198.75014349 198.60512722 235.4312225 ]]

iteration 4
[[ 18.84182543  89.89765175 248.71555162]
 [ 13.2962963  193.01513341 231.63878933]
 [198.72954893 198.40558104 235.53707951]]

iteration 5
[[ 19.01885057  87.61149425 248.5816092 ]
 [ 13.21544402 191.66332046 232.31351351]
 [198.67659981 198.40592168 235.52416428]]

iteration 6
[[ 19.13755869  86.34553991 248.51220657]
 [ 13.07829723 190.88597491 232.67008742]
 [198.60545906 198.41210155 235.51059362]]

iteration 7
[[ 19.16729858

True

### img3 k == 10

In [88]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import cv2  # redd and show the image 
import random as r


# to use for image read/write/show processing
#!pip install opencv-python

arr = cv2.imread("img3.jpg")




arr2D = arr.reshape((arr.shape[0]*arr.shape[1],3)) # 
print(arr2D.shape)



### Initialization of k Centroids

k = 10   # Select centroids from the give image pixels
centroids = np.zeros((k,3))
for i in range(k):
    
    row_idx = r.randint(0,arr.shape[0])
    
    centroids[i,:] = arr2D[row_idx,:]
    
print(centroids)

import heapq  # to store the min distance centroid efficiently 


# 

clusters_arr = np.zeros((arr2D.shape[0],3))

for i in range(50):
    selected_centroid_row = np.zeros(arr2D.shape[0])
    
    for row in range(arr2D.shape[0]):  # CALCULATE THE DISTANCE FOR EACH PIXEL,FROM EACH DISTANCE 
        min_dis_centroids = [] 
        for clus in range(k):
            #print(clus)
            #print(np.sum(np.abs(row - centroids[clus,:])))
            dist = np.sum(np.abs(arr2D[row] - centroids[clus,:])) # CALCULATE THE DISTANCE
            # 
            heapq.heappush(min_dis_centroids, (dist, clus) )  #make min heap on
                                                     # basis tuple[0]("Cluster distance") index, also store the cluster name
                                                     # to get min cluster and its name easily


        #heapq.heapify(min_dis_centroids)
        #print(min_dis_centroids)
        #print(min_dis_centroids[0][1])
       
        selected_centroid_row[row] = min_dis_centroids[0][1] # min distance value on the zero index,(tuple)[1] for "cluster NO"
    print('iteration',i)
  
    print(centroids)
    print()
    for c in range(k): # 
        
        group_rows = arr2D[selected_centroid_row == c]
        
        centroids[c,:] = np.mean(group_rows,axis=0) # Update the centroids WITH MEAN OF SAME CLUSTER (i.e c1, c2)
print('Finished: ') 
print('final centroids ',centroids)

centroids # Centroids 

# UPDATE The Pixels color finally according to clusteres


for c in range(k):
    arr2D[selected_centroid_row == c] = centroids[c]

arr2D.shape = (arr.shape[0],arr.shape[1],arr.shape[2])


# Arange Shape of Array for image 

arr2D = arr2D.reshape(arr.shape)

cv2.imshow('image',arr2D) # not showing array

# DOWNLOAD THE IMAGE 

cv2.imwrite('img3_k10.jpg', arr2D)













(10000, 3)
[[ 18.  73. 254.]
 [ 17.  77. 251.]
 [ 10.  73. 253.]
 [ 13.  74. 255.]
 [186. 173. 253.]
 [  8. 153. 255.]
 [ 23.  75. 252.]
 [180. 168. 255.]
 [ 12. 153. 255.]
 [ 17.  74. 255.]]
iteration 0
[[ 18.  73. 254.]
 [ 17.  77. 251.]
 [ 10.  73. 253.]
 [ 13.  74. 255.]
 [186. 173. 253.]
 [  8. 153. 255.]
 [ 23.  75. 252.]
 [180. 168. 255.]
 [ 12. 153. 255.]
 [ 17.  74. 255.]]

iteration 1
[[ 17.33774834  67.06622517 250.87417219]
 [ 15.49785408  80.24463519 250.24892704]
 [  6.95173454  71.92156863 245.66666667]
 [ 12.99186992  77.66666667 254.4796748 ]
 [206.71573245 206.8372586  231.25812529]
 [  2.74331551 180.83890374 227.17312834]
 [ 35.04125737  86.94302554 245.31434185]
 [159.94350282 162.63276836 252.22410546]
 [ 22.60897436 188.89458689 243.35185185]
 [ 17.45132743  76.22123894 254.79646018]]

iteration 2
[[ 16.40092166  62.85714286 247.60829493]
 [ 13.57342657  90.88811189 249.6048951 ]
 [  3.07333333  72.35333333 237.60666667]
 [  9.70689655  88.42145594 253.72030651]


iteration 19
[[ 13.70397112  62.23826715 247.48736462]
 [  9.56338028 145.10328638 251.67605634]
 [  4.90225564  64.08270677 224.14285714]
 [ 85.34057971 115.19565217 243.51449275]
 [218.47983707 218.84847251 219.34256619]
 [ 16.47547974 185.01492537 209.66950959]
 [163.46065699 167.37509549 250.42933537]
 [197.53456537 191.92950034 249.54346338]
 [ 12.39675516 204.25294985 243.61356932]
 [ 17.10200927  80.33230294 250.88408037]]

iteration 20
[[ 13.35714286  62.84693878 247.91156463]
 [  9.51648352 145.19466248 251.66562009]
 [  5.08148148  63.97777778 224.26666667]
 [ 87.60583942 116.78832117 243.94890511]
 [218.42345277 218.85179153 219.34690554]
 [ 16.76931217 185.17142857 209.72698413]
 [164.3454142  167.74038462 250.47485207]
 [198.07648725 192.44192635 249.52478754]
 [ 12.24888889 204.24222222 243.72296296]
 [ 17.37831513  80.56786271 250.80109204]]

iteration 21
[[ 13.18412698  63.43174603 248.22222222]
 [  9.51648352 145.19466248 251.66562009]
 [  5.08148148  63.97777778 224.2

iteration 38
[[ 13.98644338  75.71770335 251.47208931]
 [  9.78159126 145.05928237 251.67862715]
 [  6.94230769  63.20673077 230.11538462]
 [108.34722222 185.91203704 222.88425926]
 [220.07666527 219.04105572 219.19857562]
 [  9.5        183.96153846 209.74009324]
 [166.23153409 167.48579545 251.15980114]
 [199.11751663 193.65779749 249.18773097]
 [ 12.05196733 204.26206385 243.69636229]
 [ 42.20121951  93.63109756 245.18292683]]

iteration 39
[[ 14.17046347  75.89080911 251.45483111]
 [  9.6546875  145.0796875  251.6734375 ]
 [  6.94230769  63.20673077 230.11538462]
 [107.60663507 189.55450237 220.69194313]
 [220.13668763 219.03647799 219.19371069]
 [  9.22429907 183.9614486  209.81775701]
 [165.94279661 167.29872881 251.1779661 ]
 [199.11751663 193.65779749 249.18773097]
 [ 12.02752976 204.27157738 243.74479167]
 [ 44.0477707   94.54458599 245.        ]]

iteration 40
[[ 14.55030488  76.27134146 251.44969512]
 [  9.52738654 145.09859155 251.66823161]
 [  6.94230769  63.20673077 230.1

True

### img3 k = 20

In [89]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import cv2  # redd and show the image 
import random as r


# to use for image read/write/show processing
#!pip install opencv-python

arr = cv2.imread("img3.jpg")




arr2D = arr.reshape((arr.shape[0]*arr.shape[1],3)) # 
print(arr2D.shape)



### Initialization of k Centroids

k = 20   # Select centroids from the give image pixels
centroids = np.zeros((k,3))
for i in range(k):
    
    row_idx = r.randint(0,arr.shape[0])
    
    centroids[i,:] = arr2D[row_idx,:]
    
print(centroids)

import heapq  # to store the min distance centroid efficiently 


# 

clusters_arr = np.zeros((arr2D.shape[0],3))

for i in range(50):
    selected_centroid_row = np.zeros(arr2D.shape[0])
    
    for row in range(arr2D.shape[0]):  # CALCULATE THE DISTANCE FOR EACH PIXEL,FROM EACH DISTANCE 
        min_dis_centroids = [] 
        for clus in range(k):
            #print(clus)
            #print(np.sum(np.abs(row - centroids[clus,:])))
            dist = np.sum(np.abs(arr2D[row] - centroids[clus,:])) # CALCULATE THE DISTANCE
            # 
            heapq.heappush(min_dis_centroids, (dist, clus) )  #make min heap on
                                                     # basis tuple[0]("Cluster distance") index, also store the cluster name
                                                     # to get min cluster and its name easily


        #heapq.heapify(min_dis_centroids)
        #print(min_dis_centroids)
        #print(min_dis_centroids[0][1])
       
        selected_centroid_row[row] = min_dis_centroids[0][1] # min distance value on the zero index,(tuple)[1] for "cluster NO"
    print('iteration',i)
  
    print(centroids)
    print()
    for c in range(k): # 
        
        group_rows = arr2D[selected_centroid_row == c]
        
        centroids[c,:] = np.mean(group_rows,axis=0) # Update the centroids WITH MEAN OF SAME CLUSTER (i.e c1, c2)
print('Finished: ') 
print('final centroids ',centroids)

centroids # Centroids 

# UPDATE The Pixels color finally according to clusteres


for c in range(k):
    arr2D[selected_centroid_row == c] = centroids[c]

arr2D.shape = (arr.shape[0],arr.shape[1],arr.shape[2])


# Arange Shape of Array for image 

arr2D = arr2D.reshape(arr.shape)

cv2.imshow('image',arr2D) # not showing array

# DOWNLOAD THE IMAGE 

cv2.imwrite('img3_k20.jpg', arr2D)













(10000, 3)
[[ 21. 150. 253.]
 [ 16.  74. 255.]
 [ 20.  74. 251.]
 [164. 168. 246.]
 [176. 171. 255.]
 [ 18.  78. 251.]
 [  8. 151. 255.]
 [ 79.  99. 230.]
 [ 13.  75. 253.]
 [  8.  74. 253.]
 [180. 168. 255.]
 [ 17.  71. 255.]
 [169. 172. 246.]
 [ 19.  74. 255.]
 [176. 172. 248.]
 [ 12.  74. 252.]
 [ 18.  78. 251.]
 [182. 169. 255.]
 [182. 170. 252.]
 [ 19.  71. 255.]]
iteration 0
[[ 21. 150. 253.]
 [ 16.  74. 255.]
 [ 20.  74. 251.]
 [164. 168. 246.]
 [176. 171. 255.]
 [ 18.  78. 251.]
 [  8. 151. 255.]
 [ 79.  99. 230.]
 [ 13.  75. 253.]
 [  8.  74. 253.]
 [180. 168. 255.]
 [ 17.  71. 255.]
 [169. 172. 246.]
 [ 19.  74. 255.]
 [176. 172. 248.]
 [ 12.  74. 252.]
 [ 18.  78. 251.]
 [182. 169. 255.]
 [182. 170. 252.]
 [ 19.  71. 255.]]

iteration 1
[[ 22.23298969 189.47010309 242.47113402]
 [ 15.89166667  76.53333333 254.53333333]
 [ 24.55555556  70.28472222 242.8125    ]
 [150.79306358 167.57572254 246.66936416]
 [174.15525114 173.38812785 254.26484018]
 [ 24.29810298  84.95121951 248.

iteration 10
[[ 13.08034934 203.72489083 247.38777293]
 [ 18.03655914  77.20860215 252.59354839]
 [ 32.58536585  79.14634146 234.3902439 ]
 [151.2278481  155.02531646 253.30886076]
 [164.08237986 168.13729977 250.19450801]
 [ 62.78787879  98.3030303  235.25757576]
 [  8.48817408 188.20719016 212.4512772 ]
 [102.625      127.54545455 249.46590909]
 [  9.20846906 145.63680782 251.61237785]
 [  1.04347826  62.86956522 220.88043478]
 [180.55309735 176.45132743 249.83185841]
 [  7.74736842  56.41052632 242.04210526]
 [108.64324324 203.75135135 215.05405405]
 [ 26.85585586  93.62162162 253.27477477]
 [234.16539197 227.34512428 223.51816444]
 [  8.60773481  78.39226519 251.24493554]
 [         nan          nan          nan]
 [200.61974249 194.21802575 250.72446352]
 [208.46912704 212.14620298 216.57345635]
 [ 15.31428571  63.62285714 249.56      ]]

iteration 11
[[ 12.33681672 204.0233119  245.60209003]
 [ 18.03655914  77.20860215 252.59354839]
 [ 32.58536585  79.14634146 234.3902439 ]
 [151.

iteration 20
[[ 11.90223881 204.26940299 243.81716418]
 [ 18.03655914  77.20860215 252.59354839]
 [ 32.58536585  79.14634146 234.3902439 ]
 [151.3573201  155.18610422 253.32506203]
 [164.43487859 169.21192053 249.82560706]
 [ 62.78787879  98.3030303  235.25757576]
 [  9.12895662 183.80187573 209.75732708]
 [102.625      127.54545455 249.46590909]
 [  9.25806452 145.92741935 251.64516129]
 [  1.04347826  62.86956522 220.88043478]
 [180.74169184 176.55287009 249.81873112]
 [  7.74736842  56.41052632 242.04210526]
 [106.85945946 203.63783784 214.84324324]
 [ 26.85585586  93.62162162 253.27477477]
 [235.57330416 228.8107221  224.18599562]
 [  8.60773481  78.39226519 251.24493554]
 [         nan          nan          nan]
 [200.58001693 194.31160034 250.4165961 ]
 [210.10986842 212.69934211 216.59605263]
 [ 15.31428571  63.62285714 249.56      ]]

iteration 21
[[ 11.90223881 204.26940299 243.81716418]
 [ 18.03655914  77.20860215 252.59354839]
 [ 32.58536585  79.14634146 234.3902439 ]
 [151.

iteration 30
[[ 11.90223881 204.26940299 243.81716418]
 [ 18.03655914  77.20860215 252.59354839]
 [ 32.58536585  79.14634146 234.3902439 ]
 [151.3573201  155.18610422 253.32506203]
 [164.43487859 169.21192053 249.82560706]
 [ 62.78787879  98.3030303  235.25757576]
 [  9.12895662 183.80187573 209.75732708]
 [102.625      127.54545455 249.46590909]
 [  9.25806452 145.92741935 251.64516129]
 [  1.04347826  62.86956522 220.88043478]
 [180.74169184 176.55287009 249.81873112]
 [  7.74736842  56.41052632 242.04210526]
 [106.85945946 203.63783784 214.84324324]
 [ 26.85585586  93.62162162 253.27477477]
 [235.57330416 228.8107221  224.18599562]
 [  8.60773481  78.39226519 251.24493554]
 [         nan          nan          nan]
 [200.58001693 194.31160034 250.4165961 ]
 [210.10986842 212.69934211 216.59605263]
 [ 15.31428571  63.62285714 249.56      ]]

iteration 31
[[ 11.90223881 204.26940299 243.81716418]
 [ 18.03655914  77.20860215 252.59354839]
 [ 32.58536585  79.14634146 234.3902439 ]
 [151.

iteration 40
[[ 11.90223881 204.26940299 243.81716418]
 [ 18.03655914  77.20860215 252.59354839]
 [ 32.58536585  79.14634146 234.3902439 ]
 [151.3573201  155.18610422 253.32506203]
 [164.43487859 169.21192053 249.82560706]
 [ 62.78787879  98.3030303  235.25757576]
 [  9.12895662 183.80187573 209.75732708]
 [102.625      127.54545455 249.46590909]
 [  9.25806452 145.92741935 251.64516129]
 [  1.04347826  62.86956522 220.88043478]
 [180.74169184 176.55287009 249.81873112]
 [  7.74736842  56.41052632 242.04210526]
 [106.85945946 203.63783784 214.84324324]
 [ 26.85585586  93.62162162 253.27477477]
 [235.57330416 228.8107221  224.18599562]
 [  8.60773481  78.39226519 251.24493554]
 [         nan          nan          nan]
 [200.58001693 194.31160034 250.4165961 ]
 [210.10986842 212.69934211 216.59605263]
 [ 15.31428571  63.62285714 249.56      ]]

iteration 41
[[ 11.90223881 204.26940299 243.81716418]
 [ 18.03655914  77.20860215 252.59354839]
 [ 32.58536585  79.14634146 234.3902439 ]
 [151.

True